openapi: 3.0.0
info:
  title: Sample spec
  version: 1.0.0

tags:
  - name: Users
    description: User account endpoints

paths:

  /users:
    get:
      tags: [ Users ]
      summary: List users

      parameters:
        - name: limit
          in: query
          description: Limit
          required: false
          schema:
            type: number
            default: 30
        - name: offset
          in: query
          description: Offser
          required: false
          schema:
            type: number
            default: 0

      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchUserResponse'

    post:
      tags: [ Users ]
      summary: Create user

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'

      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'


components:
[SCHEMAS]
